/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import org.junit.Test;


/**
 * Model tests for BotEventLog
 */
public class BotEventLogTest {
    private final BotEventLog model = new BotEventLog();

    /**
     * Model tests for BotEventLog
     */
    @Test
    public void testBotEventLog() {
        // TODO: test BotEventLog
    }

    /**
     * Test the property 'botId'
     */
    @Test
    public void botIdTest() {
        // TODO: test botId
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'event'
     */
    @Test
    public void eventTest() {
        // TODO: test event
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'datetime'
     */
    @Test
    public void datetimeTest() {
        // TODO: test datetime
    }

}
