/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import com.github.motoki317.traq4j.model.ChannelStatsStamp;
import com.github.motoki317.traq4j.model.ChannelStatsUser;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ChannelStats
 */
public class ChannelStatsTest {
    private final ChannelStats model = new ChannelStats();

    /**
     * Model tests for ChannelStats
     */
    @Test
    public void testChannelStats() {
        // TODO: test ChannelStats
    }

    /**
     * Test the property 'totalMessageCount'
     */
    @Test
    public void totalMessageCountTest() {
        // TODO: test totalMessageCount
    }

    /**
     * Test the property 'stamps'
     */
    @Test
    public void stampsTest() {
        // TODO: test stamps
    }

    /**
     * Test the property 'users'
     */
    @Test
    public void usersTest() {
        // TODO: test users
    }

    /**
     * Test the property 'datetime'
     */
    @Test
    public void datetimeTest() {
        // TODO: test datetime
    }

}
