/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import org.junit.Test;


/**
 * Model tests for ForcedNotificationChangedEvent
 */
public class ForcedNotificationChangedEventTest {
    private final ForcedNotificationChangedEvent model = new ForcedNotificationChangedEvent();

    /**
     * Model tests for ForcedNotificationChangedEvent
     */
    @Test
    public void testForcedNotificationChangedEvent() {
        // TODO: test ForcedNotificationChangedEvent
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'force'
     */
    @Test
    public void forceTest() {
        // TODO: test force
    }

}
