/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OAuth2Prompt
 */
public class OAuth2PromptTest {
    /**
     * Model tests for OAuth2Prompt
     */
    @Test
    public void testOAuth2Prompt() {
        // TODO: test OAuth2Prompt
    }

}
