/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import org.junit.Test;


/**
 * Model tests for ParentChangedEvent
 */
public class ParentChangedEventTest {
    private final ParentChangedEvent model = new ParentChangedEvent();

    /**
     * Model tests for ParentChangedEvent
     */
    @Test
    public void testParentChangedEvent() {
        // TODO: test ParentChangedEvent
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'before'
     */
    @Test
    public void beforeTest() {
        // TODO: test before
    }

    /**
     * Test the property 'after'
     */
    @Test
    public void afterTest() {
        // TODO: test after
    }

}
