/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import org.junit.Test;


/**
 * Model tests for PatchChannelSubscribersRequest
 */
public class PatchChannelSubscribersRequestTest {
    private final PatchChannelSubscribersRequest model = new PatchChannelSubscribersRequest();

    /**
     * Model tests for PatchChannelSubscribersRequest
     */
    @Test
    public void testPatchChannelSubscribersRequest() {
        // TODO: test PatchChannelSubscribersRequest
    }

    /**
     * Test the property 'on'
     */
    @Test
    public void onTest() {
        // TODO: test on
    }

    /**
     * Test the property 'off'
     */
    @Test
    public void offTest() {
        // TODO: test off
    }

}
