/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import org.junit.Test;


/**
 * Model tests for PatchStampPaletteRequest
 */
public class PatchStampPaletteRequestTest {
    private final PatchStampPaletteRequest model = new PatchStampPaletteRequest();

    /**
     * Model tests for PatchStampPaletteRequest
     */
    @Test
    public void testPatchStampPaletteRequest() {
        // TODO: test PatchStampPaletteRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'stamps'
     */
    @Test
    public void stampsTest() {
        // TODO: test stamps
    }

}
