/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import org.junit.Test;


/**
 * Model tests for PatchMeRequest
 */
public class PatchMeRequestTest {
    private final PatchMeRequest model = new PatchMeRequest();

    /**
     * Model tests for PatchMeRequest
     */
    @Test
    public void testPatchMeRequest() {
        // TODO: test PatchMeRequest
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'twitterId'
     */
    @Test
    public void twitterIdTest() {
        // TODO: test twitterId
    }

    /**
     * Test the property 'bio'
     */
    @Test
    public void bioTest() {
        // TODO: test bio
    }

    /**
     * Test the property 'homeChannel'
     */
    @Test
    public void homeChannelTest() {
        // TODO: test homeChannel
    }

}
