/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import org.junit.Test;


/**
 * Model tests for PinRemovedEvent
 */
public class PinRemovedEventTest {
    private final PinRemovedEvent model = new PinRemovedEvent();

    /**
     * Model tests for PinRemovedEvent
     */
    @Test
    public void testPinRemovedEvent() {
        // TODO: test PinRemovedEvent
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'messageId'
     */
    @Test
    public void messageIdTest() {
        // TODO: test messageId
    }

}
