/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import org.junit.Test;


/**
 * Model tests for PostWebRTCAuthenticateRequest
 */
public class PostWebRTCAuthenticateRequestTest {
    private final PostWebRTCAuthenticateRequest model = new PostWebRTCAuthenticateRequest();

    /**
     * Model tests for PostWebRTCAuthenticateRequest
     */
    @Test
    public void testPostWebRTCAuthenticateRequest() {
        // TODO: test PostWebRTCAuthenticateRequest
    }

    /**
     * Test the property 'peerId'
     */
    @Test
    public void peerIdTest() {
        // TODO: test peerId
    }

}
