/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import org.junit.Test;


/**
 * Model tests for PostClipFolderRequest
 */
public class PostClipFolderRequestTest {
    private final PostClipFolderRequest model = new PostClipFolderRequest();

    /**
     * Model tests for PostClipFolderRequest
     */
    @Test
    public void testPostClipFolderRequest() {
        // TODO: test PostClipFolderRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

}
