/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PostLinkExternalAccount
 */
public class PostLinkExternalAccountTest {
    private final PostLinkExternalAccount model = new PostLinkExternalAccount();

    /**
     * Model tests for PostLinkExternalAccount
     */
    @Test
    public void testPostLinkExternalAccount() {
        // TODO: test PostLinkExternalAccount
    }

    /**
     * Test the property 'providerName'
     */
    @Test
    public void providerNameTest() {
        // TODO: test providerName
    }

}
