/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import org.junit.Test;


/**
 * Model tests for PutChannelSubscribeLevelRequest
 */
public class PutChannelSubscribeLevelRequestTest {
    private final PutChannelSubscribeLevelRequest model = new PutChannelSubscribeLevelRequest();

    /**
     * Model tests for PutChannelSubscribeLevelRequest
     */
    @Test
    public void testPutChannelSubscribeLevelRequest() {
        // TODO: test PutChannelSubscribeLevelRequest
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

}
