/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import com.github.motoki317.traq4j.model.UserAccountState;
import com.github.motoki317.traq4j.model.UserTag;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UserDetail
 */
public class UserDetailTest {
    private final UserDetail model = new UserDetail();

    /**
     * Model tests for UserDetail
     */
    @Test
    public void testUserDetail() {
        // TODO: test UserDetail
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'bot'
     */
    @Test
    public void botTest() {
        // TODO: test bot
    }

    /**
     * Test the property 'iconFileId'
     */
    @Test
    public void iconFileIdTest() {
        // TODO: test iconFileId
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'twitterId'
     */
    @Test
    public void twitterIdTest() {
        // TODO: test twitterId
    }

    /**
     * Test the property 'lastOnline'
     */
    @Test
    public void lastOnlineTest() {
        // TODO: test lastOnline
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'groups'
     */
    @Test
    public void groupsTest() {
        // TODO: test groups
    }

    /**
     * Test the property 'bio'
     */
    @Test
    public void bioTest() {
        // TODO: test bio
    }

    /**
     * Test the property 'homeChannel'
     */
    @Test
    public void homeChannelTest() {
        // TODO: test homeChannel
    }

}
