/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import org.junit.Test;


/**
 * Model tests for WebRTCUserStateSessions
 */
public class WebRTCUserStateSessionsTest {
    private final WebRTCUserStateSessions model = new WebRTCUserStateSessions();

    /**
     * Model tests for WebRTCUserStateSessions
     */
    @Test
    public void testWebRTCUserStateSessions() {
        // TODO: test WebRTCUserStateSessions
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'sessionId'
     */
    @Test
    public void sessionIdTest() {
        // TODO: test sessionId
    }

}
