/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * チャンネル
 */
@ApiModel(description = "チャンネル")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-05T13:16:54.379Z[GMT]")
public class Channel {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_PARENT_ID = "parentId";
  @SerializedName(SERIALIZED_NAME_PARENT_ID)
  private UUID parentId;

  public static final String SERIALIZED_NAME_ARCHIVED = "archived";
  @SerializedName(SERIALIZED_NAME_ARCHIVED)
  private Boolean archived;

  public static final String SERIALIZED_NAME_FORCE = "force";
  @SerializedName(SERIALIZED_NAME_FORCE)
  private Boolean force;

  public static final String SERIALIZED_NAME_TOPIC = "topic";
  @SerializedName(SERIALIZED_NAME_TOPIC)
  private String topic;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_CHILDREN = "children";
  @SerializedName(SERIALIZED_NAME_CHILDREN)
  private List<UUID> children = new ArrayList<UUID>();


  public Channel id(UUID id) {
    
    this.id = id;
    return this;
  }

   /**
   * チャンネルUUID
   * @return id
  **/
  @ApiModelProperty(required = true, value = "チャンネルUUID")

  public UUID getId() {
    return id;
  }


  public void setId(UUID id) {
    this.id = id;
  }


  public Channel parentId(UUID parentId) {
    
    this.parentId = parentId;
    return this;
  }

   /**
   * 親チャンネルUUID
   * @return parentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "親チャンネルUUID")

  public UUID getParentId() {
    return parentId;
  }


  public void setParentId(UUID parentId) {
    this.parentId = parentId;
  }


  public Channel archived(Boolean archived) {
    
    this.archived = archived;
    return this;
  }

   /**
   * チャンネルがアーカイブされているかどうか
   * @return archived
  **/
  @ApiModelProperty(required = true, value = "チャンネルがアーカイブされているかどうか")

  public Boolean getArchived() {
    return archived;
  }


  public void setArchived(Boolean archived) {
    this.archived = archived;
  }


  public Channel force(Boolean force) {
    
    this.force = force;
    return this;
  }

   /**
   * 強制通知チャンネルかどうか
   * @return force
  **/
  @ApiModelProperty(required = true, value = "強制通知チャンネルかどうか")

  public Boolean getForce() {
    return force;
  }


  public void setForce(Boolean force) {
    this.force = force;
  }


  public Channel topic(String topic) {
    
    this.topic = topic;
    return this;
  }

   /**
   * チャンネルトピック
   * @return topic
  **/
  @ApiModelProperty(required = true, value = "チャンネルトピック")

  public String getTopic() {
    return topic;
  }


  public void setTopic(String topic) {
    this.topic = topic;
  }


  public Channel name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * チャンネル名
   * @return name
  **/
  @ApiModelProperty(required = true, value = "チャンネル名")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Channel children(List<UUID> children) {
    
    this.children = children;
    return this;
  }

  public Channel addChildrenItem(UUID childrenItem) {
    this.children.add(childrenItem);
    return this;
  }

   /**
   * 子チャンネルのUUID配列
   * @return children
  **/
  @ApiModelProperty(required = true, value = "子チャンネルのUUID配列")

  public List<UUID> getChildren() {
    return children;
  }


  public void setChildren(List<UUID> children) {
    this.children = children;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Channel channel = (Channel) o;
    return Objects.equals(this.id, channel.id) &&
        Objects.equals(this.parentId, channel.parentId) &&
        Objects.equals(this.archived, channel.archived) &&
        Objects.equals(this.force, channel.force) &&
        Objects.equals(this.topic, channel.topic) &&
        Objects.equals(this.name, channel.name) &&
        Objects.equals(this.children, channel.children);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, parentId, archived, force, topic, name, children);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Channel {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("    force: ").append(toIndentedString(force)).append("\n");
    sb.append("    topic: ").append(toIndentedString(topic)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

