/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import java.util.Objects;
import java.util.Arrays;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.UUID;

/**
 * チャンネル強制通知状態変更イベント
 */
@ApiModel(description = "チャンネル強制通知状態変更イベント")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-18T11:58:46.174904Z[Etc/UTC]")
public class ForcedNotificationChangedEvent {
    public static final String SERIALIZED_NAME_USER_ID = "userId";
    @SerializedName(SERIALIZED_NAME_USER_ID)
    private UUID userId;

    public static final String SERIALIZED_NAME_FORCE = "force";
    @SerializedName(SERIALIZED_NAME_FORCE)
    private Boolean force;


    public ForcedNotificationChangedEvent userId(UUID userId) {

        this.userId = userId;
        return this;
    }

    /**
     * 変更者UUID
     *
     * @return userId
     **/
    @ApiModelProperty(required = true, value = "変更者UUID")

    public UUID getUserId() {
        return userId;
    }


    public void setUserId(UUID userId) {
        this.userId = userId;
    }


    public ForcedNotificationChangedEvent force(Boolean force) {

        this.force = force;
        return this;
    }

    /**
     * 変更後強制通知状態
     *
     * @return force
     **/
    @ApiModelProperty(required = true, value = "変更後強制通知状態")

    public Boolean getForce() {
        return force;
    }


    public void setForce(Boolean force) {
        this.force = force;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ForcedNotificationChangedEvent forcedNotificationChangedEvent = (ForcedNotificationChangedEvent) o;
        return Objects.equals(this.userId, forcedNotificationChangedEvent.userId) &&
                Objects.equals(this.force, forcedNotificationChangedEvent.force);
    }

    @Override
    public int hashCode() {
        return Objects.hash(userId, force);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ForcedNotificationChangedEvent {\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("    force: ").append(toIndentedString(force)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

