/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * OAuth2スコープ
 */
@JsonAdapter(OAuth2Scope.Adapter.class)
public enum OAuth2Scope {
  
  READ("read"),
  
  WRITE("write"),
  
  MANAGE_BOT("manage_bot");

  private String value;

  OAuth2Scope(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OAuth2Scope fromValue(String value) {
    for (OAuth2Scope b : OAuth2Scope.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<OAuth2Scope> {
    @Override
    public void write(final JsonWriter jsonWriter, final OAuth2Scope enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public OAuth2Scope read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OAuth2Scope.fromValue(value);
    }
  }
}

