/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import java.util.Objects;
import java.util.Arrays;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;

/**
 * OGPに含まれる画像の情報
 */
@ApiModel(description = "OGPに含まれる画像の情報")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-18T11:58:46.174904Z[Etc/UTC]")
public class OgpMedia {
    public static final String SERIALIZED_NAME_URL = "url";
    @SerializedName(SERIALIZED_NAME_URL)
    private String url;

    public static final String SERIALIZED_NAME_SECURE_URL = "secureUrl";
    @SerializedName(SERIALIZED_NAME_SECURE_URL)
    private String secureUrl;

    public static final String SERIALIZED_NAME_TYPE = "type";
    @SerializedName(SERIALIZED_NAME_TYPE)
    private String type;

    public static final String SERIALIZED_NAME_WIDTH = "width";
    @SerializedName(SERIALIZED_NAME_WIDTH)
    private Integer width;

    public static final String SERIALIZED_NAME_HEIGHT = "height";
    @SerializedName(SERIALIZED_NAME_HEIGHT)
    private Integer height;


    public OgpMedia url(String url) {

        this.url = url;
        return this;
    }

    /**
     * Get url
     *
     * @return url
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getUrl() {
        return url;
    }


    public void setUrl(String url) {
        this.url = url;
    }


    public OgpMedia secureUrl(String secureUrl) {

        this.secureUrl = secureUrl;
        return this;
    }

    /**
     * Get secureUrl
     *
     * @return secureUrl
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getSecureUrl() {
        return secureUrl;
    }


    public void setSecureUrl(String secureUrl) {
        this.secureUrl = secureUrl;
    }


    public OgpMedia type(String type) {

        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getType() {
        return type;
    }


    public void setType(String type) {
        this.type = type;
    }


    public OgpMedia width(Integer width) {

        this.width = width;
        return this;
    }

    /**
     * Get width
     *
     * @return width
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getWidth() {
        return width;
    }


    public void setWidth(Integer width) {
        this.width = width;
    }


    public OgpMedia height(Integer height) {

        this.height = height;
        return this;
    }

    /**
     * Get height
     *
     * @return height
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getHeight() {
        return height;
    }


    public void setHeight(Integer height) {
        this.height = height;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OgpMedia ogpMedia = (OgpMedia) o;
        return Objects.equals(this.url, ogpMedia.url) &&
                Objects.equals(this.secureUrl, ogpMedia.secureUrl) &&
                Objects.equals(this.type, ogpMedia.type) &&
                Objects.equals(this.width, ogpMedia.width) &&
                Objects.equals(this.height, ogpMedia.height);
    }

    @Override
    public int hashCode() {
        return Objects.hash(url, secureUrl, type, width, height);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OgpMedia {\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("    secureUrl: ").append(toIndentedString(secureUrl)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    width: ").append(toIndentedString(width)).append("\n");
        sb.append("    height: ").append(toIndentedString(height)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

