/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.UUID;

/**
 * チャンネル情報変更リクエスト
 */
@ApiModel(description = "チャンネル情報変更リクエスト")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-05T13:16:54.379Z[GMT]")
public class PatchChannelRequest {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ARCHIVED = "archived";
  @SerializedName(SERIALIZED_NAME_ARCHIVED)
  private Boolean archived;

  public static final String SERIALIZED_NAME_FORCE = "force";
  @SerializedName(SERIALIZED_NAME_FORCE)
  private Boolean force;

  public static final String SERIALIZED_NAME_PARENT = "parent";
  @SerializedName(SERIALIZED_NAME_PARENT)
  private UUID parent;


  public PatchChannelRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * チャンネル名
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "チャンネル名")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public PatchChannelRequest archived(Boolean archived) {
    
    this.archived = archived;
    return this;
  }

   /**
   * アーカイブされているかどうか
   * @return archived
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "アーカイブされているかどうか")

  public Boolean getArchived() {
    return archived;
  }


  public void setArchived(Boolean archived) {
    this.archived = archived;
  }


  public PatchChannelRequest force(Boolean force) {
    
    this.force = force;
    return this;
  }

   /**
   * 強制通知チャンネルかどうか
   * @return force
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "強制通知チャンネルかどうか")

  public Boolean getForce() {
    return force;
  }


  public void setForce(Boolean force) {
    this.force = force;
  }


  public PatchChannelRequest parent(UUID parent) {
    
    this.parent = parent;
    return this;
  }

   /**
   * 親チャンネルUUID
   * @return parent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "親チャンネルUUID")

  public UUID getParent() {
    return parent;
  }


  public void setParent(UUID parent) {
    this.parent = parent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatchChannelRequest patchChannelRequest = (PatchChannelRequest) o;
    return Objects.equals(this.name, patchChannelRequest.name) &&
        Objects.equals(this.archived, patchChannelRequest.archived) &&
        Objects.equals(this.force, patchChannelRequest.force) &&
        Objects.equals(this.parent, patchChannelRequest.parent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, archived, force, parent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatchChannelRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("    force: ").append(toIndentedString(force)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

