/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import java.util.Objects;
import java.util.Arrays;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.UUID;

/**
 * 自分のユーザー情報変更リクエスト
 */
@ApiModel(description = "自分のユーザー情報変更リクエスト")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-18T11:58:46.174904Z[Etc/UTC]")
public class PatchMeRequest {
    public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
    @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
    private String displayName;

    public static final String SERIALIZED_NAME_TWITTER_ID = "twitterId";
    @SerializedName(SERIALIZED_NAME_TWITTER_ID)
    private String twitterId;

    public static final String SERIALIZED_NAME_BIO = "bio";
    @SerializedName(SERIALIZED_NAME_BIO)
    private String bio;

    public static final String SERIALIZED_NAME_HOME_CHANNEL = "homeChannel";
    @SerializedName(SERIALIZED_NAME_HOME_CHANNEL)
    private UUID homeChannel;


    public PatchMeRequest displayName(String displayName) {

        this.displayName = displayName;
        return this;
    }

    /**
     * 新しい表示名
     *
     * @return displayName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "新しい表示名")

    public String getDisplayName() {
        return displayName;
    }


    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }


    public PatchMeRequest twitterId(String twitterId) {

        this.twitterId = twitterId;
        return this;
    }

    /**
     * TwitterID
     *
     * @return twitterId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "TwitterID")

    public String getTwitterId() {
        return twitterId;
    }


    public void setTwitterId(String twitterId) {
        this.twitterId = twitterId;
    }


    public PatchMeRequest bio(String bio) {

        this.bio = bio;
        return this;
    }

    /**
     * 自己紹介(biography)
     *
     * @return bio
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "自己紹介(biography)")

    public String getBio() {
        return bio;
    }


    public void setBio(String bio) {
        this.bio = bio;
    }


    public PatchMeRequest homeChannel(UUID homeChannel) {

        this.homeChannel = homeChannel;
        return this;
    }

    /**
     * ホームチャンネルのUUID &#x60;00000000-0000-0000-0000-000000000000&#x60;を指定すると、ホームチャンネルが&#x60;null&#x60;に設定されます
     *
     * @return homeChannel
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "ホームチャンネルのUUID `00000000-0000-0000-0000-000000000000`を指定すると、ホームチャンネルが`null`に設定されます")

    public UUID getHomeChannel() {
        return homeChannel;
    }


    public void setHomeChannel(UUID homeChannel) {
        this.homeChannel = homeChannel;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PatchMeRequest patchMeRequest = (PatchMeRequest) o;
        return Objects.equals(this.displayName, patchMeRequest.displayName) &&
                Objects.equals(this.twitterId, patchMeRequest.twitterId) &&
                Objects.equals(this.bio, patchMeRequest.bio) &&
                Objects.equals(this.homeChannel, patchMeRequest.homeChannel);
    }

    @Override
    public int hashCode() {
        return Objects.hash(displayName, twitterId, bio, homeChannel);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PatchMeRequest {\n");
        sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
        sb.append("    twitterId: ").append(toIndentedString(twitterId)).append("\n");
        sb.append("    bio: ").append(toIndentedString(bio)).append("\n");
        sb.append("    homeChannel: ").append(toIndentedString(homeChannel)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

