/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;

/**
 * Webhook情報変更リクエスト
 */
@ApiModel(description = "Webhook情報変更リクエスト")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-05T14:52:47.663Z[GMT]")
public class PatchWebhookRequest {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_CHANNEL_ID = "channelId";
  @SerializedName(SERIALIZED_NAME_CHANNEL_ID)
  private UUID channelId;

  public static final String SERIALIZED_NAME_SECRET = "secret";
  @SerializedName(SERIALIZED_NAME_SECRET)
  private String secret;

  public static final String SERIALIZED_NAME_OWNER_ID = "ownerId";
  @SerializedName(SERIALIZED_NAME_OWNER_ID)
  private UUID ownerId;


  public PatchWebhookRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Webhookユーザー表示名
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Webhookユーザー表示名")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public PatchWebhookRequest description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * 説明
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "説明")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public PatchWebhookRequest channelId(UUID channelId) {
    
    this.channelId = channelId;
    return this;
  }

   /**
   * デフォルトの投稿先チャンネルUUID
   * @return channelId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "デフォルトの投稿先チャンネルUUID")

  public UUID getChannelId() {
    return channelId;
  }


  public void setChannelId(UUID channelId) {
    this.channelId = channelId;
  }


  public PatchWebhookRequest secret(String secret) {
    
    this.secret = secret;
    return this;
  }

   /**
   * Webhookシークレット
   * @return secret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Webhookシークレット")

  public String getSecret() {
    return secret;
  }


  public void setSecret(String secret) {
    this.secret = secret;
  }


  public PatchWebhookRequest ownerId(UUID ownerId) {
    
    this.ownerId = ownerId;
    return this;
  }

   /**
   * 移譲先のユーザーUUID
   * @return ownerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "移譲先のユーザーUUID")

  public UUID getOwnerId() {
    return ownerId;
  }


  public void setOwnerId(UUID ownerId) {
    this.ownerId = ownerId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatchWebhookRequest patchWebhookRequest = (PatchWebhookRequest) o;
    return Objects.equals(this.name, patchWebhookRequest.name) &&
        Objects.equals(this.description, patchWebhookRequest.description) &&
        Objects.equals(this.channelId, patchWebhookRequest.channelId) &&
        Objects.equals(this.secret, patchWebhookRequest.secret) &&
        Objects.equals(this.ownerId, patchWebhookRequest.ownerId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, channelId, secret, ownerId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatchWebhookRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

