/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * skyway用認証リクエスト
 */
@ApiModel(description = "skyway用認証リクエスト")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-05T13:16:54.379Z[GMT]")
public class PostWebRTCAuthenticateRequest {
  public static final String SERIALIZED_NAME_PEER_ID = "peerId";
  @SerializedName(SERIALIZED_NAME_PEER_ID)
  private String peerId;


  public PostWebRTCAuthenticateRequest peerId(String peerId) {
    
    this.peerId = peerId;
    return this;
  }

   /**
   * ピアID
   * @return peerId
  **/
  @ApiModelProperty(required = true, value = "ピアID")

  public String getPeerId() {
    return peerId;
  }


  public void setPeerId(String peerId) {
    this.peerId = peerId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostWebRTCAuthenticateRequest postWebRTCAuthenticateRequest = (PostWebRTCAuthenticateRequest) o;
    return Objects.equals(this.peerId, postWebRTCAuthenticateRequest.peerId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(peerId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostWebRTCAuthenticateRequest {\n");
    sb.append("    peerId: ").append(toIndentedString(peerId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

