/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.github.motoki317.traq4j.JSON;

/**
 * スタンプパレット作成リクエスト
 */
@ApiModel(description = "スタンプパレット作成リクエスト")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-21T02:01:01.991892Z[Etc/UTC]")
public class PostStampPaletteRequest {
  public static final String SERIALIZED_NAME_STAMPS = "stamps";
  @SerializedName(SERIALIZED_NAME_STAMPS)
  private Set<UUID> stamps = new LinkedHashSet<>();

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public PostStampPaletteRequest() { 
  }

  public PostStampPaletteRequest stamps(Set<UUID> stamps) {
    
    this.stamps = stamps;
    return this;
  }

  public PostStampPaletteRequest addStampsItem(UUID stampsItem) {
    this.stamps.add(stampsItem);
    return this;
  }

   /**
   * パレット内のスタンプのUUID配列
   * @return stamps
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "パレット内のスタンプのUUID配列")

  public Set<UUID> getStamps() {
    return stamps;
  }


  public void setStamps(Set<UUID> stamps) {
    this.stamps = stamps;
  }


  public PostStampPaletteRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * パレット名
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "パレット名")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public PostStampPaletteRequest description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * 説明
   * @return description
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "説明")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostStampPaletteRequest postStampPaletteRequest = (PostStampPaletteRequest) o;
    return Objects.equals(this.stamps, postStampPaletteRequest.stamps) &&
        Objects.equals(this.name, postStampPaletteRequest.name) &&
        Objects.equals(this.description, postStampPaletteRequest.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stamps, name, description);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostStampPaletteRequest {\n");
    sb.append("    stamps: ").append(toIndentedString(stamps)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("stamps");
    openapiFields.add("name");
    openapiFields.add("description");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("stamps");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("description");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PostStampPaletteRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (PostStampPaletteRequest.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in PostStampPaletteRequest is not found in the empty JSON string", PostStampPaletteRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!PostStampPaletteRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PostStampPaletteRequest` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PostStampPaletteRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (jsonObj.get("stamps") != null && !jsonObj.get("stamps").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `stamps` to be an array in the JSON string but got `%s`", jsonObj.get("stamps").toString()));
      }
      if (jsonObj.get("name") != null && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (jsonObj.get("description") != null && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostStampPaletteRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostStampPaletteRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostStampPaletteRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostStampPaletteRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<PostStampPaletteRequest>() {
           @Override
           public void write(JsonWriter out, PostStampPaletteRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PostStampPaletteRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PostStampPaletteRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PostStampPaletteRequest
  * @throws IOException if the JSON string is invalid with respect to PostStampPaletteRequest
  */
  public static PostStampPaletteRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostStampPaletteRequest.class);
  }

 /**
  * Convert an instance of PostStampPaletteRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

