/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.github.motoki317.traq4j.JSON;

/**
 * VersionFlags
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-21T02:01:01.991892Z[Etc/UTC]")
public class VersionFlags {
  public static final String SERIALIZED_NAME_EXTERNAL_LOGIN = "externalLogin";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_LOGIN)
  private List<String> externalLogin = new ArrayList<>();

  public static final String SERIALIZED_NAME_SIGN_UP_ALLOWED = "signUpAllowed";
  @SerializedName(SERIALIZED_NAME_SIGN_UP_ALLOWED)
  private Boolean signUpAllowed;

  public VersionFlags() { 
  }

  public VersionFlags externalLogin(List<String> externalLogin) {
    
    this.externalLogin = externalLogin;
    return this;
  }

  public VersionFlags addExternalLoginItem(String externalLoginItem) {
    this.externalLogin.add(externalLoginItem);
    return this;
  }

   /**
   * 有効な外部ログインプロバイダ
   * @return externalLogin
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "有効な外部ログインプロバイダ")

  public List<String> getExternalLogin() {
    return externalLogin;
  }


  public void setExternalLogin(List<String> externalLogin) {
    this.externalLogin = externalLogin;
  }


  public VersionFlags signUpAllowed(Boolean signUpAllowed) {
    
    this.signUpAllowed = signUpAllowed;
    return this;
  }

   /**
   * ユーザーが自身で新規登録(POST /api/v3/users)可能か
   * @return signUpAllowed
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "ユーザーが自身で新規登録(POST /api/v3/users)可能か")

  public Boolean getSignUpAllowed() {
    return signUpAllowed;
  }


  public void setSignUpAllowed(Boolean signUpAllowed) {
    this.signUpAllowed = signUpAllowed;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VersionFlags versionFlags = (VersionFlags) o;
    return Objects.equals(this.externalLogin, versionFlags.externalLogin) &&
        Objects.equals(this.signUpAllowed, versionFlags.signUpAllowed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalLogin, signUpAllowed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VersionFlags {\n");
    sb.append("    externalLogin: ").append(toIndentedString(externalLogin)).append("\n");
    sb.append("    signUpAllowed: ").append(toIndentedString(signUpAllowed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("externalLogin");
    openapiFields.add("signUpAllowed");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("externalLogin");
    openapiRequiredFields.add("signUpAllowed");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to VersionFlags
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (VersionFlags.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in VersionFlags is not found in the empty JSON string", VersionFlags.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!VersionFlags.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `VersionFlags` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : VersionFlags.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (jsonObj.get("externalLogin") != null && !jsonObj.get("externalLogin").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `externalLogin` to be an array in the JSON string but got `%s`", jsonObj.get("externalLogin").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VersionFlags.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VersionFlags' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VersionFlags> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VersionFlags.class));

       return (TypeAdapter<T>) new TypeAdapter<VersionFlags>() {
           @Override
           public void write(JsonWriter out, VersionFlags value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public VersionFlags read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of VersionFlags given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of VersionFlags
  * @throws IOException if the JSON string is invalid with respect to VersionFlags
  */
  public static VersionFlags fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VersionFlags.class);
  }

 /**
  * Convert an instance of VersionFlags to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

