/*
 * traQ v3
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.motoki317.traq4j.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.UUID;

/**
 * チャンネル可視状態変更イベント
 */
@ApiModel(description = "チャンネル可視状態変更イベント")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-05T13:16:54.379Z[GMT]")
public class VisibilityChangedEvent {
  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private UUID userId;

  public static final String SERIALIZED_NAME_VISIBILITY = "visibility";
  @SerializedName(SERIALIZED_NAME_VISIBILITY)
  private Boolean visibility;


  public VisibilityChangedEvent userId(UUID userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * 変更者UUID
   * @return userId
  **/
  @ApiModelProperty(required = true, value = "変更者UUID")

  public UUID getUserId() {
    return userId;
  }


  public void setUserId(UUID userId) {
    this.userId = userId;
  }


  public VisibilityChangedEvent visibility(Boolean visibility) {
    
    this.visibility = visibility;
    return this;
  }

   /**
   * 変更後可視状態
   * @return visibility
  **/
  @ApiModelProperty(required = true, value = "変更後可視状態")

  public Boolean getVisibility() {
    return visibility;
  }


  public void setVisibility(Boolean visibility) {
    this.visibility = visibility;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VisibilityChangedEvent visibilityChangedEvent = (VisibilityChangedEvent) o;
    return Objects.equals(this.userId, visibilityChangedEvent.userId) &&
        Objects.equals(this.visibility, visibilityChangedEvent.visibility);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, visibility);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VisibilityChangedEvent {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

